{{/* Define the hbp container */}}
{{- define "nextcloud.hpb" -}}
image: '{{ include "tc.common.images.selector" . }}'
imagePullPolicy: '{{ .Values.image.pullPolicy }}'
{{- with .Values.securityContext }}
securityContext:
  {{- tpl ( toYaml . ) $ | nindent 2 }}
{{- end }}
{{- with (include "tc.common.controller.volumeMounts" . | trim) }}
volumeMounts:
  {{ nindent 2 . }}
{{- end }}
command:
  - "/bin/sh"
  - "-c"
  - |
    /bin/bash <<'EOF'
    /var/www/html/custom_apps/notify_push/bin/x86_64/notify_push /var/www/html/config/config.php
    EOF
env:
  - name: NEXTCLOUD_URL
    value: 'http://127.0.0.1'
  - name: TRUSTED_PROXIES
    value: "{{ .Values.env.TRUSTED_PROXIES }}"
  - name: POSTGRES_DB
    value: "{{ .Values.postgresql.postgresqlDatabase }}"
  - name: POSTGRES_USER
    value: "{{ .Values.postgresql.postgresqlUsername }}"
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: dbcreds
        key: postgresql-password
  - name: POSTGRES_HOST
    valueFrom:
      secretKeyRef:
        name: dbcreds
        key: plainporthost
  - name: REDIS_HOST
    valueFrom:
      secretKeyRef:
        name: rediscreds
        key: plainhost
  - name: REDIS_HOST_PASSWORD
    valueFrom:
      secretKeyRef:
        name: rediscreds
        key: redis-password
{{- end -}}
