{{/* Define the hbp container */}}
{{- define "nextcloud.hpb" -}}
image: '{{ include "tc.common.images.selector" . }}'
imagePullPolicy: '{{ .Values.image.pullPolicy }}'
{{- with .Values.securityContext }}
securityContext:
  {{- tpl ( toYaml . ) $ | nindent 2 }}
{{- end }}
{{- with (include "tc.common.controller.volumeMounts" . | trim) }}
volumeMounts:
  {{ nindent 2 . }}
{{- end }}
command: ["sh /hbp.sh"]
env:
  NEXTCLOUD_URL: 'http://{{ include "tc.common.names.fullname" . }}'
  TRUSTED_PROXIES: "{{ .Values.env.TRUSTED_PROXIES }}"
  NEXTCLOUD_DATA_DIR: "{{ .Values.env.NEXTCLOUD_DATA_DIR }}"
  POSTGRES_DB: "{{ .Values.postgresql.postgresqlDatabase }}"
  POSTGRES_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  POSTGRES_PASSWORD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  POSTGRES_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainporthost
  REDIS_HOST:
    secretKeyRef:
      name: rediscreds
      key: plainhost
  REDIS_HOST_PASSWORD:
    secretKeyRef:
      name: rediscreds
      key: redis-password
{{- end -}}
