{{/* Make sure all variables are set properly */}}
{{- include "tc.common.loader.init" . }}

{{/* Render configmap for nextcloud */}}
{{- include "nextcloud.configmap" . }}

{{- $newMiddlewares :=  append .Values.ingress.main.fixedMiddlewares "tc-nextcloud-chain" }}
{{- $_ := set .Values.ingress.main "fixedMiddlewares" $newMiddlewares -}}

{{/* $_ := set .Values.additionalContainers "hpb" (include "nextcloud.hpb" . | fromYaml) */}}

{{/* Render cronjob for nextcloud */}}
{{- include "nextcloud.cronjob" . }}

{{/* Render the templates */}}
{{ include "tc.common.loader.apply" . }}
